# Generated by Django 2.2 on 2021-06-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_TV', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Channel',
            new_name='channel',
        ),
    ]
